USE [master]
CREATE LOGIN [User] WITH PASSWORD=N'password', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
USE [APPELMA_390bf6b01fa044f1ba015ff8693ef461]
CREATE USER [User] FOR LOGIN [User]
ALTER USER [User] WITH DEFAULT_SCHEMA=[db_owner]
ALTER ROLE [db_owner] ADD MEMBER [User]
